spring:
  application:
    name: cluSTAR

  config:
    activate:
      on-profile: dev  # 개발

  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  web:
    resources:
      add-mappings: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}

  ai:
    vectorstore:
      type: pgvector
      pgvector:
        schema-name: public
        table-name: vector_store
        dimensions: 768
        distance-type: COSINE_DISTANCE
        index-type: HNSW
        initialize-schema: false
        schema-validation: false
        remove-existing-vector-store-table: false

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expire-length: 3600000 # 60분
  refresh-expire-length: 3600000 # 1시간
  header: Authorization

app:
  cookie:
    domain: ".clustar.cloud"
    same-site: None
    secure: true

management:
  endpoint:
    health:
      show-details: always # 헬스 체크 상세 내용을 로그로 보기 위해
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    redis:
      enabled: false # Redis가 없어도 전체 앱은 UP 상태로 유지

cloud:
  aws:
    s3:
      bucket: clustar-bucket-01
